### ISSUE TITLE
cut tags based on ruby version for openshift/origi

### ISSUE THREAD

**Issue by gabemontero** [openshift/ruby-hello-world#123]
@bparees - @adambkaplan had a good idea to help avoid the recent openshift/origin e2e breakage when @vrutkovs did his 2.5 to 2.7 migration

cut a tag like ruby-2.7, and then we can change the openshift/origin e2e's that pull in this repo to use that ref vs. the master branch ref

then next time we could bump the ruby version here first, cut a new tag, and then update openshift/origin, where in the interim existing job runs would still point to the old tag

WDYT ?

**Comment by bparees** [comment]
honestly i'd rather just fork this repo elsewhere and move the tests to use the fork.  One of the main problems w/ this repo is that it is both a public example *and* required for certain tests.  Once upon a time we considered that a benefit (we ensure we don't break our public facing example) but now i'm more inclined to have a clear distinction/indication that "this repo is used by tests, don't change it unless you understand the tests that consume it"

**Comment by bparees** [comment]
(note that either approach requires a bunch of test updates being backported through all the release branches)

**Comment by gabemontero** [comment]
> (note that either approach requires a bunch of test updates being backported through all the release branches)

yep understood, but those existing tests would not be broken in the interim

**Comment by gabemontero** [comment]
> honestly i'd rather just fork this repo elsewhere and move the tests to use the fork. One of the main problems w/ this repo is that it is both a public example _and_ required for certain tests. Once upon a time we considered that a benefit (we ensure we don't break our public facing example) but now i'm more inclined to have a clear distinction/indication that "this repo is used by tests, don't change it unless you understand the tests that consume it"

sure ... the question is where exactly, in particular which org vs. github.com/openshift ?  

create a new one?

github.com/redhat-developer?

we do not want to do somebody's personal repo, right?

**Comment by bparees** [comment]
> the question is where exactly, in particular which org vs. github.com/openshift ?

might as well be openshift org.

> we do not want to do somebody's personal repo, right?

right

If tagging is easier, i'm fine with that as the path of least resistance.  Note that you could also just use an explicit commit rather than a branch or tag, if you go that path.  And then just update the commit ref as needed.

**Comment by gabemontero** [comment]
> > the question is where exactly, in particular which org vs. github.com/openshift ?
> 
> might as well be openshift org.
> 
> > we do not want to do somebody's personal repo, right?
> 
> right
> 
> If tagging is easier, i'm fine with that as the path of least resistance. Note that you could also just use an explicit commit rather than a branch or tag, if you go that path. And then just update the commit ref as needed.

true ... the human readability could be viewed as a thing.  Remembering a year from now that commit is there cause we are aligned with ruby-2.7, whereas it is obvious from the tag
