### ISSUE TITLE
New branch needed in order to fix a build test for ARM

### ISSUE THREAD

**Issue by yselkowitz** [openshift/ruby-hello-world#131]
The config branch is currently used by the `[sig-builds][Feature:Builds][Slow] starting a build using CLI  start-build test context Trigger builds with branch refs matching directories on master branch Should checkout the config branch, not config directory` test.  That branch is way behind master, and in order to fix this test for ARM which only has modern versions of ruby and only for UBI8, it would have to be [significantly updated](https://github.com/openshift/ruby-hello-world/compare/config...multi-arch:config).  However, that would break the test, which [uses the commit message](https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L404-L406) to verify the branch checked out.

Therefore, unless I'm missing something, in order to fix this test, there are two options:

1. Create a new branch here off of master whose name matches a different directory in the repo, e.g. 'test'.  Then someone creates a PR to distinguish this branch from master (e.g. [remove the README](https://github.com/openshift/ruby-hello-world/pull/61)).  Finally, update that test in origin in master/4.9+ with s/config/test/g and the new commit message.
2. Merge the changes into the current config branch, then update the commit message in the test in origin, and backport that to all applicable stable branches.

Option 1 seems cleaner, but afaik I can't make a PR to create a new branch, so I'll need your help for that in addition to the subsequent reviews.  Please let me know how you want to proceed.

**Comment by bparees** [comment]
@yselkowitz you just want a new branch that's up to date with master but has the README removed? i can do that if so.

**Comment by yselkowitz** [comment]
Basically, but for the purposes of the test in question, the branch name has to match a directory name in the repo (e.g. 'test') and its tip has to have a unique commit message.

**Comment by bparees** [comment]
here you go:
https://github.com/openshift/ruby-hello-world/tree/test

i removed README.md in that branch.

**Comment by bparees** [comment]
though now i'm wondering if we couldn't have just rebased the existing `config` branch?

**Comment by yselkowitz** [comment]
That would be option 2 above, but would have resulted in a change to the commit message at the tip of the branch, which would cause the test in question to fail on all OpenShift versions until we backported a fix through all the still-supported branches in origin.

**Comment by bparees** [comment]
> That would be option 2 above, but would have resulted in a change to the commit message at the tip of the branch

pretty sure i should be able to make it happen w/o changing the commit message.

**Comment by yselkowitz** [comment]
Can you rebase merge commits in git?  Usually when you rebase, merge commits are dropped.

**Comment by bparees** [comment]
> Can you rebase merge commits in git? Usually when you rebase, merge commits are dropped.

i can just push directly to the openshift:config branch.  Since the test just cares about the commit text, i can just make the text match.

**Comment by bparees** [comment]
e.g. i just created this one:
https://github.com/openshift/ruby-hello-world/tree/newconfig

i should be able to do the same to the existing config branch

**Comment by yselkowitz** [comment]
I guess there was a third option after all.  If you're comfortable with that approach, then by all means, and you can drop the 'test' branch.  Thanks!

**Comment by bparees** [comment]
done:
https://github.com/openshift/ruby-hello-world/tree/config

**Comment by yselkowitz** [comment]
The test in question still passes in CI, so we should be set.  Thanks!
