### ISSUE TITLE
osc new-app deployment

### ISSUE THREAD

**Issue by sebiwi** [openshift/ruby-hello-world#38]
This doesn't seems to work using the new-app command from http://docs.openshift.org/latest/dev_guide/new_app.html. It tried to connect to a local mysql service, which doesn't seems to exists.

**Comment by bparees** [comment]
Can you please list the exact new-app commands you ran?  None of the samples in that doc create both the application and the database service together, so you'd have to run 2 of the commands, or run a different form that creates both the app and the services ("osc new-app [source-repository] mysql" i believe):

$ osc new-app https://github.com/openshift/ruby-hello-world mysql
deploymentConfigs/mysql
imageStreams/ruby-hello-world
buildConfigs/ruby-hello-world
services/mysql
A build was created - you can run `osc start-build ruby-hello-world` to start it.
Service "mysql" created at 172.30.215.116 with port mappings 3306->3306, 8080->8080.
