### ISSUE TITLE
database is not created by default

### ISSUE THREAD

**Issue by chmouel** [openshift/ruby-hello-world#54]
Tried for the first time origin and running the command advised after issuing a new-project to launch ruby-hello-world : 

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git

and it does not seem to create a database with it (I was under impression it did when trying with OSE). It would be nice to document this in the README how to add a database to the application, for example I this : 

```
MYSQL_PASSWORD=moto
MYSQL_USER=hello
MYSQL_DATABASE=hellomoto

oc new-app centos/mysql-56-centos7:latest -e MYSQL_PASSWORD=${MYSQL_PASSWORD} -e MYSQL_USER=${MYSQL_USER} -e MYSQL_DATABASE=${MYSQL_DATABASE} --name=mysql
oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git -e DATABASE_SERVICE_HOST=mysql \
    -e MYSQL_USER=${MYSQL_USER} -e MYSQL_PASSWORD=${MYSQL_PASSWORD} -e  MYSQL_DATABASE=${MYSQL_DATABASE}

```

**Comment by bparees** [comment]
did you follow the instructions pointed to by the main readme?
https://github.com/openshift/origin/blob/master/examples/sample-app/README.md

those instructions have you use a template to launch the app, which creates the DB service and all the env variables.

**Comment by chmouel** [comment]
Hello, yes I have seen it but that README goes over a full install of OpenShift (which arguably the user has already) and a a lot of advanced  concepts, from a new user experience that just created a new project it may be more attractive for them to show that in only two commands you can add a Database to your app and connect your app to it, they can dig further for the full sample app, what do you think?

**Comment by bparees** [comment]
I still don't think we should be describing commands to add a database, the right way to stand up this particular application is via the existing template which creates both the app and the db and links them together.  Does it make sense to have another section that skips over all the "standing up openshift" bits and basically starts at step 12 of the existing readme?  I suppose I could see some value there.

if you want a good example of how to add a DB to an existing app, we just got a great pull against the nodejs-ex example that covers adding a DB to a running app:
https://github.com/openshift/nodejs-ex/pull/44

**Comment by bparees** [comment]
@chmouel i'm going to update the new-project message so it points to a repo that doesn't expect a DB:
https://github.com/openshift/origin/pull/8590

i think that is better than trying to include a lengthy example of adding a DB to an application in the new-project output text.

**Comment by chmouel** [comment]
yes perfect! thanks
