### ISSUE TITLE
Help update Dockerfile to adjust docker build with ruby-25-rhel7 image

### ISSUE THREAD

**Issue by xiuwang** [openshift/ruby-hello-world#80]
Hi, anyone could help update Dockerfile to adjust docker build with ruby-25-rhel7?
Since from 4.2, the openshift/ruby:2.2 imagestreamtag is end of life in openshift cluster.
Thanks~

**Comment by wewang58** [comment]
@adambkaplan @gabemontero @coreydaley anyone takes time to update this to be compatible with ruby 2.5, now our qe ci automation failed of this, though I saw it's in todo e2e list: https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L284, thanks very much.

**Comment by adambkaplan** [comment]
@wewang58 you can probably give this a shot yourselves, we'd be happy to review a PR.

What you'll need to do is as follows:

1. Switch the `Dockerfile` to use the `ruby-25-centos7` image
2. On a machine or container with ruby 2.5, update the `Gemfile` to use compatible versions of the gems. Run `bundle install` and commit the resulting `Gemfile` and `Gemfile.lock` files.
3. Submit a PR with the results.

**Comment by pvalena** [comment]
Implemented in #85 AFAICT.
